### ISSUE TITLE
media-sound/deadbeef-0.7.0 @ x86_64

### ISSUE THREAD

**Issue by doertedev** [megabaks/stuff#75] opened 2016-02-10 09:40 UTC
Oy. First of all: Love your repo.

Second: 

/tmp/portage/media-sound/deadbeef-0.7.0/temp/build.log says:
```
➜  ~  cat /tmp/portage/media-sound/deadbeef-0.7.0/temp/build.log
!!! Fetched file: deadbeef-0.7.0.tar.bz2 VERIFY FAILED!
!!! Reason: Insufficient data for checksum verification
!!! Got:      
!!! Expected: MD5 RMD160 SHA1 SHA256 SHA512 WHIRLPOOL
 * Fetch failed for 'media-sound/deadbeef-0.7.0', Log file:
 *  '/tmp/portage/media-sound/deadbeef-0.7.0/temp/build.log'
```
What happened? :)

Greetings.

**Comment by istitov** [comment] 2016-02-10 11:44
Dunno. Do you have Manifest file in `media-sound/deadbeef` in repo?
It should be located somewhere like `/var/lib/layman/stuff/media-sound/deadbeef/Manifest`
Could you `cat` it here?

**Comment by istitov** [comment] 2016-02-10 11:44
Ah, ja. And thank you for the good words about the repo :-)

**Comment by istitov** [comment] 2016-02-17 11:56
hey there, I couldn't reproduce this problem.
Given no feedback from you, I just close this bug...

**Closed by istitov** 2016-02-17 11:56 UTC

**Comment by doertedev** [comment] 2016-02-17 12:30
Just went through without probs. Dont know what went wrong. Thanks a bunch. ;)

**Comment by istitov** [comment] 2016-02-17 12:34
Good!..
